controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    arm_no_wrist_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: forward_command_controller/ForwardCommandController
    
    wrist_controller:
      type: forward_command_controller/ForwardCommandController


arm_no_wrist_controller:
  ros__parameters:
    joints:
      - joint_axis_1
      - joint_axis_2
      - joint_axis_3
      - joint_axis_4

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    # Optional but commonly useful:
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: false

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint_axis_1: { trajectory: 0.2, goal: 0.1 }
      joint_axis_2: { trajectory: 0.2, goal: 0.1 }
      joint_axis_3: { trajectory: 0.2, goal: 0.1 }
      joint_axis_4: { trajectory: 0.2, goal: 0.1 }

gripper_controller:
  ros__parameters:
    joints:
      - joint_finger_1
      - joint_finger_2
      - joint_finger_3
    interface_name: position

wrist_controller:
  ros__parameters:
    joints:
      - joint_axis_5
    interface_name: velocity