moveit_servo:
  ros__parameters:
    use_sim_time: true

    # MoveIt info
    move_group_name: "arm"  # Added quotes for safety
    planning_frame: "base_link"
    ee_frame_name: "link_5_endeff_1"
    robot_link_command_frame: "base_link"

    # Command input
    command_in_type: "twist_stamped"
    cartesian_command_in_topic: "/servo_node/delta_twist_cmds"

    # Output / execution
    command_out_type: "trajectory_msgs/JointTrajectory"
    command_out_topic: "/servo_node/servo_command"
    publish_command_out: true
    publish_joint_positions: true
    publish_joint_velocities: false
    publish_joint_accelerations: false
    status_topic: "/servo_node/status"