controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["Revolute 5", "Revolute 6", "Revolute 7"]
    right_wheel_names: ["Revolute 8", "Revolute 9", "Revolute 10"]

    wheel_separation: 0.672   # track width
    wheel_radius: 0.115 

    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true

    publish_rate: 50.0
    use_stamped_vel: false
    cmd_vel_timeout: 0.25
