controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names:
      - joint_wheel_l1
      - joint_wheel_l2
      - joint_wheel_l3
    right_wheel_names:
      - joint_wheel_r1
      - joint_wheel_r2
      - joint_wheel_r3

    use_sim_time: true

    wheel_separation: 0.67   # track width
    wheel_radius: 0.11 

    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: false    # robot_localization publishes odom->base_footprint (via fixed base_footprint<->base_link)

    publish_rate: 50.0
    use_stamped_vel: false
    cmd_vel_timeout: 0.25
